define({
    "ERR_LOADING" : "טעינה נכשלה :(",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "פתח את מנהל החיבורים",
    "SIDEPANEL_FILETREE_NAME" : "שם",
    "SIDEPANEL_FILETREE_SIZE" : "גודל",
    "SIDEPANEL_FILETREE_TYPE" : "סוג",
    "SIDEPANEL_FILETREE_MODIFIED" : "Modified",
    "SIDEPANEL_CONDISCONNECT" : "התחבר/התנתק",
    "SIDEPANEL_REFRESH" : "רענון",
    "SIDEPANEL_RELOADSETTINGS" : "Reload Settings & Re-enter Password",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "שרת לא קיים",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Looks like this server doesn't exist.<br>Check Server filed in connection settings.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "Can't Reach Server",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "I just can't reach server.<br>Maybe your Firewall don't let me do this.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Incorrect Authorization Data",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "I can't authorize with those login and password you gave me.<br>Please check them.",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "Can't find connection",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "There are no eqFTP connections tied with current project and no connected server.<br>Connect to server or specify current project's folder as local path for connection in Settings.",
    "ERR_DIAG_ECONNRESET_TITLE" : "Server denying connections",
    "ERR_DIAG_ECONNRESET_CONTENT" : "I can't connect to server, it doesn't allows me.<br>Try restart Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "You've been disconnected from server",
    "ERR_DIAG_ECONNABORTED_CONTENT" : "Connection aborted. Trying to reconnect...",
    "ERR_DIAG_UNIVERSAL_TITLE" : "There's an error",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "Look at this error! How could it happen?",
    "ERR_DIAG_NORSAKEYFOUND" : "There's no RSA key found in: ",

    "NOT_DIAG_CONNECTED" : "Connected to server.",
    "NOT_DIAG_DISCONNECTED" : "Disconnected from server.",
    "NOT_DIAG_FILESDIFFERENT" : "There's a difference between local and remote files. Click here for more actions.",

    "PASSWDWIND_TITLE" : "אנא הכנס את הסיסמה שלך",
    "PASSWDWIND_CONTENT" : "הסיסמה שלך עבור eqFTP:",

    "CHECKDIFF_TITLE" : "קיים שוני בין הקבצים",
    "CHECKDIFF_CONTENT" : "הקובץ המרוחק והקובץ המקומי שונים. אנא בחר את הפעולה שברצונך לעשות.",
    "CHECKDIFF_BUTTON_COMPARE" : "השווה קבצים",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "הצג שינויים",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "השאר מקומי",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "השאר עותקים מקומיים לתור הנוכחי",
    "CHECKDIFF_BUTTON_GETREMOTE" : "קבל מרוחק",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "קבל עותקים מרוחקים לתור הנוכחי",

    "SETTINGSWIND_TITLE" : "eqFTP מנהל החיבורים",
    "SETTINGSWIND_ERR_BLANKS" : "Oops! Looks like something is wrong. Check input fields and try again.",
    "SETTINGSWIND_ERR_CANTWRITE" : "Something went totally wrong! I can't write settings to file!",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "The path you're trying to insert is currently in use by another connection.",
    "SETTINGSWIND_NOTIF_DONE" : "הכל נשמר! :)",
    "SETTINGSWIND_SAVEDCONN" : "חיבורי FTP שמורים",
    "SETTINGSWIND_DELETECONN_HOVER" : "מחק חיבור זה",
    "SETTINGSWIND_COPYCONN_HOVER" : "העתק חיבור זה",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "אתה לא יכול למחוק חיבור שנמצא בשימוש כעת",
    "SETTINGSWIND_ADDCONN_HOVER" : "הוסף חיבור חדש",
    "SETTINGSWIND_ADDCONN_STRING" : "צור חיבור חדש...",
    "SETTINGSWIND_DELETECONNCONF_1" : "אנא אשר מחיקה של ", // Those 2 strings are going like this: SETTINGSWIND_DELETECONNCONF_1 + VAL + SETTINGSWIND_DELETECONNCONF_2
    "SETTINGSWIND_DELETECONNCONF_2" : " חיבור.", // So if in your language there's no need in 2 strings, just leave one of them blank
    "SETTINGSWIND_OPENGLOBSET" : "פתח הגדרות FTP גלובליות...",
    "SETTINGSWIND_NOTHINGYETMSG" : "Choose connection in sidebar for editing or create new.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Folder For Projects:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Directory for Projects with Downloaded Files:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Folder For Settings:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Directory for Settings File",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Don't Open Projects after Download",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "סיסמת על",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "שם החיבור:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "הכנס את שם החיבור",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "שרת:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "סוג פרוטוקול:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "שם משתמש:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "שם משתמש FTP",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "סיסמה:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "סיסמת FTP",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "מפתח RSA",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "לחץ לבחירת מפתח RSA",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Choose path to RSA key",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Remote Path:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Type in the remote path to the project root folder",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Local Path:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Creates new folder in default location if blank",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "העלאת הקובץ בשמירה",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Add to paused queue.",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Even If Disconnected",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "This option automatically connects to a server when a saved file is opened from the server or a saved file is within the current project and this project was created by this ftp extension. Oh, I really hope I explained it well...",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Insert current project's path",
    "SETTINGSWIND_GLOB_FRM_TITLE" : "Choose folder retrieving method:",
    "SETTINGSWIND_GLOB_FRM_LIST" : "Use LIST command",
    "SETTINGSWIND_GLOB_FRM_MLSD" : "Use MLSD command",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Keep alive interval:", // Keep Alive is feature when client sends empty packages to server to prevet disconnection.
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Value in seconds. Recommended value is 10. Use zero to forbid keep alive commands and disconnect from server every time command is done.",
    "SETTINGSWIND_GLOB_DEBUG" : "Debug:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "פורמט תאריך:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "אמריקאי",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "אירופי",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "אסיה",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "נקה תור אוטומטית",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "התראות",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Time Offset:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Use this option to set correct time for Modified column",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "חיבור",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "אוטומיזציה",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "מתקדם",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "קבע אוטומיזציה:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "סינכרון",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "קלאסי",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "בחר מה לסנכרן",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "יצירת קובץ",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "יצירת תיקיה",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "עדכון קובץ",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "שינוי שם",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "העברה",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "מחיקה",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "הגדרות נוספות",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "בדוק לשינויים",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "When you open local or remote file",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Ignore list",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "Same syntax as in .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Open related Local project after switching connection and vice versa",
    "SETTINGS_NOTIF_RELOADED" : "Settings were successfully reloaded.",
    "SETTINGS_ERROR_RELOADED" : "Can't reload settings.",
    "SETTINGSWIND_GLOB_SCE_TITLE" : "Use SSH commands with SFTP",

    "QUEUE_TITLE" : "eqFTP תור",
    "QUEUE_HEADER_NAME" : "שם",
    "QUEUE_HEADER_PATH" : "Path",
    "QUEUE_HEADER_FROM" : "Source Path",
    "QUEUE_HEADER_TO" : "Destination Path",
    "QUEUE_HEADER_STATUS" : "מצב",
    "QUEUE_CLEARQ" : "נקה תור",
    "QUEUE_STARTQ" : "התחל תור",
    "QUEUE_PAUSEQ" : "השהה תור",
    "QUEUE_RESTARTQ" : "התחל נכשלים מחדש",
    "QUEUE_CONTEXTM_STARTT" : "התחל",
    "QUEUE_CONTEXTM_PAUSET" : "השהה",
    "QUEUE_CONTEXTM_REMOVET" : "הסר",
    "QUEUE_CONTEXTM_RESTARTT" : "הפעלה מחדש",
    "QUEUE_TASK_STATUS_WAITING" : "ממתין",
    "QUEUE_TASK_STATUS_SUCCESS" : "סיום",
    "QUEUE_TASK_STATUS_FAIL" : "נכשל",
    "QUEUE_TASK_STATUS_PAUSE" : "מושהה",
    "QUEUE_TASK_STATUS_STARTED" : "מתחיל",
    "QUEUE_TASK_STATUS_DELETED" : "נמחק",
    "QUEUE_DONT_ADD_COMPLETED" : "נקה אוטומטית משימוש שהסתיימו",
    
    "ERR_FILE_ACCESSDENIED" : "Access denied. Check file's permissions.",
    "ERR_FILE_AUTHORIZATION" : "Authorization Error. Check your login & password.",
    "ERR_FILE_SERVNOEXIST" : "Server Doesn't Exist. Maybe you mistyped it.",
    "ERR_FILE_SERVCANTREACH" : "Can't Reach Server. Check Firewall.",
    "ERR_FILE_FILESIZE0" : "Can't download file. Filesize is 0.",
    "ERR_FILE_DOWNLOAD" : "Can't download file.",
    "ERR_FILE_UPLOAD" : "Can't upload file.",
    "ERR_FILE_DOESNTEXIST" : "File doesn't exist",
    "ERR_FILE_CANTRENAME" : "Can't rename file: ",
    "ERR_FILE_CANTDELETE" : "Can't delete file: ",
    "ERR_FILE_CANTCREATEDIR" : "Can't create folder: ",
    "ERR_FILE_CANTDELETEDIR" : "Can't delete folder: ",
    "ERR_FILE_CANTCREATEFILE" : "Can't create file: ",
    "ERR_FILE_CANTGETINDIRECTORY" : "Can't get in directory. Check your Remote Path setting, existence of directory on server and rights to read it.<br>The directory is:", //NEW
    "ERR_FOLDER_OPEN" : "התרחשה שגיאה בעת פתיחת התיקיה כפרוייקט",

    "CONTEXTM_DOWNLOAD" : "הורדה",
    "CONTEXTM_UPLOAD" : "העלאה",
    "CONTEXTM_ADDQUEUE" : "הוסף לתור",
    "CONTEXTM_OPEN" : "פתח",
    "CONTEXTM_DELETE" : "מחק",
    "CONTEXTM_RENAME" : "שנה שם",
    "CONTEXTM_REDOWNLOAD" : "הורד מהשרת",
    "CONTEXTM_CREATEFILE" : "צור קובץ",
    "CONTEXTM_CREATEFOLDER" : "צור תיקיה",

    "OTHER_SELECT_SERVER_DROPDOWN" : "בחר שרת מרוחק לחיבור...",
    "OTHER_ERROR" : "שגיאה",
    "OTHER_PAUSED" : "מושהה",
    "OTHER_COMPLETED" : "הסתיים",
    "OTHER_CANCELLED" : "בוטל",
    "OTHER_WAITING" : "ממתין",
    "OTHER_YES" : "כן",
    "OTHER_NO" : "לא",
    "OTHER_OK" : "אישור",
    "OTHER_OFF" : "Off",
    "OTHER_CANCEL" : "ביטול",
    "OTHER_APPLY" : "החל",
    "OTHER_SAVE" : "שמור",
    "OTHER_CLOSE" : "סגור",
    "OTHER_DELETE" : "מחר",
    "OTHER_COPY" : "העתק", //NEW
    "OTHER_CONFIRM_DELETE" : "אתה בטוח שברצונך למחוק?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "There are some unsaved changes that will be lost if you click OK.<br>Do you want to proceed?",
    "OTHER_ERROR_EVENDISCONN" : "Can't upload file. 'Even If Disconnected' option is off.",
    "OTHER_ERROR_CANTREADSETTINGS" : "Can't read settings file. You probably mistyped your master password."
});
